### ISSUE TITLE
base64toFile is not a function

### ISSUE THREAD

**Issue by Bernard-Murphy** [azzlkn/node-base64-to-file#4]
There appears to be a typo or some kind of mistake with the exports in this module. The default export is an object with one key named "default", which is a function that performs the intended actions of the package. 

The following, pulled from the docs, does *not* work, and will throw the error "base64toFile is not a function":

`const base64toFile = require('node-base64-to-file');

// create an image with the a given name ie 'image'
try {
  const imagePath = await base64toFile(base64String, { filePath: './uploads', fileName: "image", types: ['png'], fileMaxSize: 3145728 });
  console.log(imagePath)
} catch (error) {
  console.log(error)
}
`

The following *does* work:

`const base64toFile = require('node-base64-to-file');

// create an image with the a given name ie 'image'
try {
  const imagePath = await base64toFile.default(base64String, { filePath: './uploads', fileName: "image", types: ['png'], fileMaxSize: 3145728 });
  console.log(imagePath)
} catch (error) {
  console.log(error)
}`

**Comment by azzlkn** [comment]
Hello Bernard, I solved the error you mentioned by adding new export methods and I published it. Thank you for letting me know, have a good year 👋
